api/urls.py
#
# Copyright (C) 2019 Authlete, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific
# language governing permissions and limitations under the
# License.


from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('authorization',          views.authorization),
    path('authorization/decision', views.authorization_decision, name='authorization_decision'),
    path('jwks',                   views.jwks),
    path('introspection',          views.introspection),
    path('revocation',             views.revocation),
    path('token',                  views.token),
    path('userinfo/',              views.userinfo),
    path('userupdates/',           views.handle_user_updates, name='handle_user_updates'),
    path('_user/<str:username>',   views.handle_user, name='handle_user'),
    path('_users/<int:page>/',     views.handle_users, name='handle_users'),
    path('_de_users/',             views.deactivate_users, name='deactivate_users'),
    path('_deact_user/<str:username>/', views.deactivate_user, name='deactivate_user'),
    path('_act_user/<str:username>/', views.activate_user, name='activate_user'),
    path('_ruser/<str:username>/', views.remove_user, name='remove_user'),
]

django_oauth_server/urls.py
from django.contrib import admin
from django.urls    import include, path
from api.views      import configuration, userinfo, root

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',   include('api.urls')),
    path('.well-known/openid-configuration', configuration),
    path('configuration/', configuration),
    path('', root)
]

api/models.py
from django.db import models

# Create your models here.

api/views.py
#
# Copyright (C) 2019 Authlete, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific
# language governing permissions and limitations under the
# License.


from django.conf                         import settings
from django.views.decorators.csrf        import csrf_exempt
from django.views.decorators.http        import require_GET, require_POST, require_http_methods
from authlete.django.handler             import *
from .authorization_decision_endpoint    import AuthorizationDecisionEndpoint
from .authorization_endpoint             import AuthorizationEndpoint
from .introspection_endpoint             import IntrospectionEndpoint
from .spi.token_request_handler_spi_impl import TokenRequestHandlerSpiImpl
from .user_info import UserInfo, Root, CreateUser
from django.http import JsonResponse


@csrf_exempt
@require_http_methods(['GET', 'POST'])
def authorization(request):
    """Authorization Endpoint"""
    return AuthorizationEndpoint(settings.AUTHLETE_API).handle(request)


@require_POST
def authorization_decision(request):
    """Authorization Decision Endpoint"""
    return AuthorizationDecisionEndpoint(settings.AUTHLETE_API).handle(request)


@require_GET
def configuration(request):
    """Discovery Endpoint (.well-known/openid-configuration)"""
    return ConfigurationRequestHandler(settings.AUTHLETE_API).handle(request)


@require_POST
@csrf_exempt
def introspection(request):
    """Introspection Endpoint"""
    return IntrospectionEndpoint(settings.AUTHLETE_API).handle(request)


@require_GET
def jwks(request):
    """JWK Set Endpoint"""
    return JwksRequestHandler(settings.AUTHLETE_API).handle(request)


@require_POST
@csrf_exempt
def revocation(request):
    """Revocation Endpoint"""
    return RevocationRequestHandler(settings.AUTHLETE_API).handle(request)


@require_POST
@csrf_exempt
def token(request):
    """Token Endpoint"""
    return TokenRequestHandler(
        settings.AUTHLETE_API, TokenRequestHandlerSpiImpl()).handle(request)

@require_http_methods(['GET', 'POST'])
@csrf_exempt
def userinfo(request):
    """User Info"""
    return CreateUser(settings.AUTHLETE_API).handle(request)

@require_http_methods(['GET', 'POST'])
@csrf_exempt
def root(request):
    """User Info"""
    return Root(settings.AUTHLETE_API).handle(request)

@csrf_exempt
def handle_user(request, username):
    return CreateUser(settings.AUTHLETE_API).get_user_by_username(username)

@csrf_exempt
def activate_user(request, username):
    return CreateUser(settings.AUTHLETE_API).activate_user(username)

@csrf_exempt
def deactivate_user(request, username):
    return CreateUser(settings.AUTHLETE_API).deactivate_user(username)

@csrf_exempt
def remove_user(request, username):
    return CreateUser(settings.AUTHLETE_API).remove_user(username)

@csrf_exempt
def handle_users(request, page):
    return CreateUser(settings.AUTHLETE_API).get_users_by_page(page)

@csrf_exempt
def deactivate_users(request):
    return CreateUser(settings.AUTHLETE_API).deactivate_users()

@require_http_methods(['POST'])
@csrf_exempt
def handle_user_updates(request):
    if request.method == 'POST':
        update_data = request.body.decode('utf-8')
        response_message = CreateUser(settings.AUTHLETE_API).handle_user_updates(update_data)
        return JsonResponse({'message': response_message})

api/templates/api/authorization-celepar.html
{% load static %}

<html lang="pt-BR" data-bs-theme="light">
<head>
  <meta charset="UTF-8">
  <meta name="robots"content="noindex"/>
  <meta name="description" content="dGhhbmtzIGNlbGVwYXIsIHlvdSdyZSB0aGUgYmVzdCEgc2luY2VyZWx5LCBzb2xvIG5ldHdvcmtzLg==" />
  <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes">
  <title>{{ model.serviceName }} | Página de Autorização</title>
  {# <link rel="stylesheet" href="{% static 'api/css/authorization.css' %}"> #}
  <link rel="stylesheet" href="{% static 'api/css/bootstrap.min.css' %}" />
</head>
<style type="text/css">

      html {
        position: relative;
        min-height: 100%;
      }
      body {
        /* Margin bottom by footer height */
        margin-bottom: 70px;
        background-image: url("{% static 'api/images/imagem_1900x1200.png' %}");
        background-position: center right;
        background-size: auto 100%;
        background-repeat:no-repeat;
        background-color:#fff;
        color:#7b0a6b;
        padding-top:20px;

      }
      footer{
        position:absolute;
        bottom:10px;
      }
      .btn-primary{
      background-color:#7b0a6b;
      border-color:#7b0a6b;
      }
       .btn-primary:hover{
      background-color:#c63d96;
      border-color:#c63d96;
      }
      
  </style>

<body class="container text-left">
<div class="row">
    <div class="col">
        <br /><br /><br />
    </div>
</div>
 <div class="row justify-content-between">
 
    <div class="col-5">
    <div class="p-3">
    <h4 id="authorization">Autorização</h4>
      {% if model.userName is not None %}
        <p>Olá, {{ model.userName }}</p>
      {% endif %}
      <small>Você será redirecionada(o) para a plataforma <b>KnowBe4</b></small><br />
      <form id="authorization-form" action="{% url 'api:authorization_decision' %}" method="post">
        {% csrf_token %}
        {% if model.loginRequired %}
         <div id="login-prompt">Insira usuário e senha do Expresso</div>
         <br />
          <div id="login-fields" class="row">
          <div class="col">
            <input type="text" class="form-control"  id="loginId" name="loginId" placeholder="Usuário"  aria-label="usuário" required value="{{ model.loginId }}"  {{ model.loginIdReadOnly }}>
            <span id="usernameError" style="color: red; display: none;">Digite um usuário válido. Endereços de email não são permitidos.</span>
          </div>
          <div class="col">
            <input type="password" class="form-control"  id="password" name="password" placeholder="Senha" aria-label="senha" required>
            <input type="hidden" name='uri' default={{ uri }} value={{ uri }}>
          </div>
        </div>
        {% endif %}
        <br />
        {% if message %}
          <div class="alert alert-warning" role="alert">
              <b>{{ message }}
          </div>
        {% endif %}
    <br />
        <div  id="authorization-form-buttons" class="row">
          <div class="col">
          <button type="submit" class="btn btn-primary " name="authorized" id="authorize-button" value="Authorize">Acessar </button>
          <button type="reset" class=" btn btn-dark " id="clean-button">Limpar</button>
        </div>
      </div>
     </form>

     {{ model.serviceName }}<br />

      {% if model.scopes is not None %}
      <span id="permissions"><strong>Permissões</strong></span><br />
        permissões solicitadas:<br />
        
          {% for scope in model.scopes %}
            &bull; <small>{{ scope.name }}: {{ scope.description }}</small><br />
          {% endfor %}
        {% endif %}
        {% if model.clientUri is not None %}
            <small class="text-body-secondary"><a target="_blank" href="{{ model.clientUri }}">Homepage</small><br />
          {% endif %}
          {% if model.policyUri is not None %}
            <small class="text-body-secondary"><a target="_blank" href="{{ model.policyUri }}">Policy</small><br />
          {% endif %}
          {% if model.tosUri is not None %}
            <small class="text-body-secondary"><a target="_blank" href="{{ model.tosUri }}">Terms of Service</a></small><br />
          {% endif %}
          <small class="text-body-secondary"> {{ model.serviceName }} | {{ model.clientName }} | {{ model.description }}</small><br />

    </div>


    </div>
    <div class="col-4 text-light-emphasys">

      

    </div>

</div>
<footer > 

</footer>
  
<script src="{% static 'api/js/bootstrap.bundle.min.js' %}" ></script>
<script type="text/javascript">
  document.getElementById('authorization-form').addEventListener('submit', function (e) {
      var username = document.getElementById('loginId').value;
      var usernameError = document.getElementById('usernameError');

      // Regex for validating email format
      var emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

      if (emailRegex.test(username)) {
          // If username is an email, prevent form submission and show error message
          e.preventDefault();
          usernameError.style.display = 'block';
      } else {
          // If username is not an email, hide any previous error message
          usernameError.style.display = 'none';
      }
  });
</script>
</body>
</html>

api/templates/api/authorization.html
{% load static %}
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes">
  <title>{{ model.serviceName }} | Authorization Page</title>
  <link rel="stylesheet" href="{% static 'api/css/authorization.css' %}">
</head>
<body class="font-default">
  <div id="page_title">{{ model.serviceName }}</div>

  <div id="content">
    <h3 id="client-name">{{ model.clientName }}</h3>
    <div class="indent">
      <img id="logo" src="{{ model.logoUri }}" alt="[Logo] (150x150)">

      <div id="client-summary">
        <p>{{ model.description }}</p>
        <ul id="client-link-list">
          {% if model.clientUri is not None %}
            <li><a target="_blank" href="{{ model.clientUri }}">Homepage</a></li>
          {% endif %}
          {% if model.policyUri is not None %}
            <li><a target="_blank" href="{{ model.policyUri }}">Policy</a></li>
          {% endif %}
          {% if model.tosUri is not None %}
            <li><a target="_blank" href="{{ model.tosUri }}">Terms of Service</a></li>
          {% endif %}
        </ul>
      </div>

      <div style="clear: both;"></div>
    </div>

    {% if model.scopes is not None %}
      <h4 id="permissions">Permissões</h4>
      <div class="indent">
        <p>A aplicação está requesitando as seguintes permissões.</p>
        <dl id="scope-list">
          <dt>Compartilhamento com App terceiros</dt>
          <dd>Compartilhar dados de e-mail, nome e sobrenome com a aplicação KnowBe4</dd>
          <!-- {% for scope in model.scopes %}
            <dt>{{ scope.name }}</dt>
            <dd>{{ scope.description }}</dd>
          {% endfor %} -->
        </dl>
      </div>
    {% endif %}

    <h4 id="authorization">Autorização</h4>
    <div class="indent">
      {% if model.userName is not None %}
        <p>Hello {{ model.userName }},</p>
      {% endif %}
      <p>Você autoriza essa aplicação?</p>

      <form id="authorization-form" action="{% url 'api:authorization_decision' %}" method="post">
        {% csrf_token %}
        {% if model.loginRequired %}
          <div id="login-fields" class="indent">
            <div id="login-prompt">Insira seu usuário e senha Celepar.</div>
            <input type="text" id="loginId" name="loginId" placeholder="Login ID"
                   class="font-default" required value="{{ model.loginId }}"
                   {{ model.loginIdReadOnly }}>
            <input type="password" id="password" name="password" placeholder="Password"
                   class="font-default" required>
          </div>
        {% endif %}
        <div id="authorization-form-buttons">
          <input type="submit" name="authorized" id="authorize-button" value="Autorizar" class="font-default"/>
        </div>
      </form>
    </div>
  </div>

</body>
</html>

api/templates/api/partials/alerts.html
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert">
        {{ message }}
    </div>
    {% endfor%}
{% endif %}